import type { Metadata } from 'next'
import Providers from '../Providers'
import { DrawerWithNavigation } from '@/components/Drawer'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {/* <Providers> */}
                    <div className='flex'>
                        <DrawerWithNavigation/>
                        <div className="flex flex-col w-full">
                        <Navbar />
                        {children}
                        </div>
                    </div>
                {/* </Providers> */}
            </body>
        </html>
    )
}
